### ISSUE TITLE
Suggested edits for Notebook 3

### ISSUE THREAD

**Issue by willingc** [mwcraig/scipy2017-jupyter-widgets-tutorial#12]
The present example in notebook 3 looked odd to me with the red `x` sort of floating.

I would consider starting with `value = True`. Then mention in text if `value = False` the red `x` for invalid will appear.

<img width="541" alt="screen shot 2017-07-03 at 2 15 20 pm" src="https://user-images.githubusercontent.com/2680980/27808097-6a13e068-5ffa-11e7-910d-c00ee29c58f9.png">

**Comment by willingc** [comment]
I realize that these are probably from the documentation from widgets but it might look cleaner if the text doesn't overrun the field. For example, Pizza toppings: becomes truncated when the widget is displayed.

<img width="623" alt="screen shot 2017-07-03 at 2 21 31 pm" src="https://user-images.githubusercontent.com/2680980/27808445-b6771680-5ffc-11e7-8523-43aeeb9d7123.png">
<img width="682" alt="screen shot 2017-07-03 at 2 24 07 pm" src="https://user-images.githubusercontent.com/2680980/27808447-b67ceb50-5ffc-11e7-9b86-209a2789906f.png">
<img width="598" alt="screen shot 2017-07-03 at 2 26 30 pm" src="https://user-images.githubusercontent.com/2680980/27808448-b67de2ee-5ffc-11e7-9919-a72d0b786d39.png">

It's not clear in these HTML widgets what the `placeholder` is doing:

<img width="588" alt="screen shot 2017-07-03 at 2 29 52 pm" src="https://user-images.githubusercontent.com/2680980/27808446-b6795bde-5ffc-11e7-81e4-4ca8833e1584.png">

**Comment by willingc** [comment]
Next link 404s

**Comment by willingc** [comment]
Truncation is discussed in Notebook 4. Perhaps reference here in the text and leave the above examples as is.

**Comment by mwcraig** [comment]
@willingc -- thanks a ton for all of these detailed comments. They are very helpful!

@jasongrout can confirm, but as far as I can tell, `placeholder` doesn't actually do anything for the HTML widgets, or for `Label`. I dropped it from those, and changed one of the `Text` widget examples to show what the placeholder does (display text until the user types in the textbox or textarea).
